### ISSUE TITLE
Error: Unrecognized data type for field

### ISSUE THREAD

**Issue by pukhalski** [defunctzombie/sequelize-encrypted#4]
Trying to use the plugin but getting unrecognized data type each time...

**Comment by defunctzombie** [comment]
Needs more info to come close to helping. Ideally a failing example.

**Comment by ryanseaton** [comment]
`// User with a secret
var EncryptedField = require('sequelize-encrypted');

module.exports = function (sequelize, DataTypes) {

  const key = process.env.DB_KEY;
  const encryptedFields = EncryptedField(sequelize, key);

  const User = sequelize.define('user', {

    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },

    // the encrypted vault (BLOB) that contains all encrypted fields
    encryptedVault: encryptedFields.vault('encryptedVault'),

    // the virtual getter/setter for the encrypted secret
    secret: encryptedFields.field('secret'),

    // the server seed hash
    name: DataTypes.STRING,

  });

  return User;
};`

and the error is

`app-0 Error: Unrecognized data type for field encryptedVault
app-0     at null.<anonymous> (/vagrant/node_modules/sequelize/lib/model.js:95:13)
app-0     at /vagrant/node_modules/lodash/lodash.js:12666:23
app-0     at /vagrant/node_modules/lodash/lodash.js:4389:15
app-0     at baseForOwn (/vagrant/node_modules/lodash/lodash.js:2652:24)
app-0     at Function.mapValues (/vagrant/node_modules/lodash/lodash.js:12665:7)
app-0     at new Model (/vagrant/node_modules/sequelize/lib/model.js:78:43)
app-0     at Sequelize.define (/vagrant/node_modules/sequelize/lib/sequelize.js:625:15)
app-0     at module.exports.DataTypes (/vagrant/server/db/models/User.js:12:32)
app-0     at Sequelize.import (/vagrant/node_modules/sequelize/lib/sequelize.js:685:30)
app-0     at /vagrant/server/db/index.js:22:33
app-0     at Array.forEach (native)
app-0     at Object.<anonymous> (/vagrant/server/db/index.js:21:27)
app-0     at Module._compile (module.js:409:26)
app-0     at Object.Module._extensions..js (module.js:416:10)
app-0     at Module.load (module.js:343:32)
app-0     at Function.Module._load (module.js:300:12)`

**Comment by ryanseaton** [comment]
@pukhalski you must include Sequelize
`const Sequelize = require('sequelize');`
